sonar.organization=soat-11
sonar.projectKey=soat-11_fiapx-terraform

sonar.sources=src/app
sonar.tests=src/tests
sonar.exclusions=venv/**,.venv/**,**/*.tf,modules/**,.terraform/**,.github/**

sonar.language=py
sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml