sonar.organization=soat-11
sonar.projectKey=soat-11_fiapx-terraform

sonar.sources=src/app
sonar.exclusions=venv/**,.venv/**,**/*.tf,modules/**,.terraform/**,.github/**

sonar.language=py
sonar.python.version=3.9


sonar.python.coverage.reportPaths=src/tests